export const WORKOUT_DATA_ACTION_TYPES = {
  SET_WORKOUT_DATA: "workout/SET_WORKOUT_DATA",
  SET_WORKOUT_NAME_TYPE: "workout/SET_WORKOUT_NAME_TYPE",
  SET_FORM_FIELDS: "workout/SET_FORM_FIELDS",
  SET_FORM_FIELDS_NAME_AND_SET: "workout/SET_FORM_FIELDS_NAME_AND_SET",
  SET_FORM_FIELDS_WEIGHT_AND_REP: "workout/SET_FORM_FIELDS_WEIGHT_AND_REP",
  CLEAR_WORKOUT: "workout/SET_CLEAR_WORKOUT",
  CLEAR_FORM_FIELDS: "workout/CLEAR_FORM_FIELDS",
};
