export const WORKOUT_DATA_ACTION_TYPES = {
  SET_WORKOUT_DATA: "workout/SET_WORKOUT_DATA",
  CAN_SUBMIT_WORKOUT: "workout/CAN_SUBMIT_WORKOUT",
  SET_WORKOUT_NAME_TYPE: "workout/SET_WORKOUT_NAME_TYPE",
  CLEAR_WORKOUT: "workout/SET_CLEAR_WORKOUT",
};
