export const USER_ACTION_TYPES = {
  // User types
  ADD_USER_TYPE: "ADD_USER_TYPE",
  SET_USER_TYPES: "SET_USER_TYPES",

  // User session
  CHECK_USER_SESSION: "CHECK_USER_SESSION",
  SET_CURRENT_USER: "SET_CURRENT_USER",

  // Sign up
  SIGN_UP_START: "SIGN_UP_START",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_FAILED: "SIGN_UP_FAILED",

  // Sign in
  SIGN_IN_START: "SIGN_IN_START",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_FAILED: "SIGN_IN_FAILED",

  // Sign out
  SIGN_OUT_START: "SIGN_OUT_START",
  SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
  SIGN_OUT_FAILED: "SIGN_OUT_FAILED",

  // Fetch workouts
  FETCH_WORKOUTS_START: "FETCH_WORKOUTS_START",
  FETCH_WORKOUTS_SUCCESS: "FETCH_WORKOUTS_SUCCESS",
  FETCH_WORKOUTS_FAILED: "FETCH_WORKOUTS_FAILED",

  // Fetch types
  FETCH_TYPES_START: "FETCH_TYPES_START",
  FETCH_TYPES_SUCCESS: "FETCH_TYPES_SUCCESS",
  FETCH_TYPES_FAILED: "FETCH_TYPES_FAILED",
};
