export const USER_ACTION_TYPES = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  SIGN_OUT_USER: "SIGN_OUT_USER",
  ADD_USER_TYPE: "ADD_USER_TYPE",
  SET_USER_TYPES: "SET_USER_TYPES",
  FETCH_WORKOUTS_START: "FETCH_WORKOUTS_START",
  FETCH_WORKOUTS_SUCCESS: "FETCH_WORKOUTS_SUCCESS",
  FETCH_TYPES_START: "FETCH_TYPES_START",
  FETCH_TYPES_SUCCESS: "FETCH_TYPES_SUCCESS",
  FETCH_FAILED: "FETCH_FAILED",
};
