export const USER_ACTION_TYPES = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  SIGN_OUT_USER: "SIGN_OUT_USER",
  SET_USER_TYPES: "SET_USER_TYPES",
  SET_USER_WORKOUTS: "SET_USER_WORKOUTS",
  ADD_USER_TYPE: "ADD_USER_TYPE",
};
